version: "3"
services:
    stat_bot:
        build: .

        environment:
            - PATH=/root/.cargo/bin:$PATH
            - QT_QPA_PLATFORM=offscreen
            - STAT_BOT_DISCORD_TOKEN=

        volumes:
            - ./data:/data
